version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: money-tracker-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: money_tracker
      MYSQL_USER: moneytracker
      MYSQL_PASSWORD: moneytracker123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
